server:
  port: 7100

spring:
  application:
    name: cloud-register-microservice
  profiles:
    active: dev

eureka:
  client:
    # 关闭自己注册自己
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:7100/eureka/
  # 关闭自我保护
  server:
    enable-self-preservation: false
  instance:
    #以IP地址注册到服务中心,相互注册使用IP地址
    prefer-ip-address: true
    #ip-address: 192.168.1.1 #强制指定IP地址，默认会获取本机的IP地址

# Logger config
logging:
  config: classpath:log4j2.xml
